Phoenix2D-Library: Phoenix::Self Class Reference
Phoenix::Self Class Reference
Phoenix Core Objects
Self
The Self lorem Ipsum
#include <Self.h>
Public Member Functions
Self (std::string player_params, std::string team_name, int unum, std::string side)
~Self ()
void addPlayerType (std::string player_type)
void processSenseBody (std::string sense_body)
void changePlayerType (int type)
void localize (std::vector< Flag > flags)
void localize ()
Static Public Member Functions
static std::string getViewModeWidthAtTime (unsigned int time)
static std::string getViewModeQualityAtTime (unsigned int time)
static double getStaminaAtTime (unsigned int time)
static double getEffortAtTime (unsigned int time)
static double getStaminaCapacityAtTime (unsigned int time)
static double getAmountOfSpeedAtTime (unsigned int time)
static double getDirectionOfSpeedAtTime (unsigned int time)
static double getHeadAngleAtTime (unsigned int time)
static int getKickCountAtTime (unsigned int time)
static int getDashCountAtTime (unsigned int time)
static int getTurnCountAtTime (unsigned int time)
static int getSayCountAtTime (unsigned int time)
static int getTurnNeckCountAtTime (unsigned int time)
static int getCatchCountAtTime (unsigned int time)
static int getMoveCountAtTime (unsigned int time)
static int getChangeViewCountAtTime (unsigned int time)
static int getArmMovableAtTime (unsigned int time)
static int getArmExpiresAtTime (unsigned int time)
static double getArmDistAtTime (unsigned int time)
static double getArmDirAtTime (unsigned int time)
static int getArmCountAtTime (unsigned int time)
static std::string getFocusTargetAtTime (unsigned int time)
static int getFocusCountAtTime (unsigned int time)
static int getTackleExpiresAtTime (unsigned int time)
static int getTackleCountAtTime (unsigned int time)
static std::list< std::string > getCollisionsAtTime (unsigned int time)
static int getFoulChargedAtTime (unsigned int time)
static std::string getFoulCardAtTime (unsigned int time)
static Position getPosition ()
static Vector2D getVelocity ()
static void setLastCommandsSet (std::list< Command * > last_commands_sent)
Static Public Attributes
static double PI = 3.14159265359
static std::string TEAM_NAME = "Phoenix2D"
static int UNIFORM_NUMBER = 1
static std::string SIDE = "l"
static int ALLOW_MULT_DEFAULT_TYPE = 0
static double CATCHABLE_AREA_L_STRECH_MAX = 1.3
static double CATCHABLE_AREA_L_STRECH_MIN = 1.0
static double DASH_POWER_RATE_DELTA_MAX = 0.0
static double DASH_POWER_RATE_DELTA_MIN = 0.0
static double EFFORT_MAX_DELTA_FACTOR = -0.004
static double EFFORT_MIN_DELTA_FACTOR = -0.004
static double EXTRA_STAMINA_DELTA_MAX = 50.0
static double EXTRA_STAMINA_DELTA_MIN = 0.0
static double FOUL_DETECT_PROBABILITY_DELTA_FACTOR = 0.0
static double INERTIA_MOMENT_DELTA_FACTOR = 25.0
static double KICK_POWER_RATE_DELTA_MAX = 0.0
static double KICK_POWER_RATE_DELTA_MIN = 0.0
static double KICK_RAND_DELTA_FACTOR = 1.0
static double KICKABLE_MARGIN_DELTA_MAX = 0.1
static double KICKABLE_MARGIN_DELTA_MIN = -0.1
static double NEW_DASH_POWER_RATE_DELTA_MAX = 0.0008
static double NEW_DASH_POWER_RATE_DELTA_MIN = -0.0012
static double NEW_STAMINA_INC_MAX_DELTA_FACTOR = -6000.0
static double PLAYER_DECAY_DELTA_MAX = 0.1
static double PLAYER_DECAY_DELTA_MIN = -0.1
static double PLAYER_SIZE_DELTA_FACTOR = -100.0
static double PLAYER_SPEED_MAX_DELTA_MAX = 0.0
static double PLAYER_SPEED_MAX_DELTA_MIN = 0.0
static int PLAYER_TYPES = 18
static int PT_MAX = 1
static int RANDOM_SEED = 1325632690
static double STAMINA_INC_MAX_DELTA_FACTOR = 0.0
static int SUBS_MAX = 3
static int TYPE_ID = 0
static double PLAYER_SPEED_MAX = 1.05
static double STAMINA_INC_MAX = 45.0
static double PLAYER_DECAY = 0.4
static double INERTIA_MOMENT = 5.0
static double DASH_POWER_RATE = 0.006
static double PLAYER_SIZE = 0.3
static double KICKABLE_MARGIN = 0.7
static double KICK_RAND = 0.1
static double EXTRA_STAMINA = 50.0
static double EFFORT_MAX = 1.0
static double EFFORT_MIN = 0.6
static double KICK_POWER_RATE = 0.027
static double FOUL_DETECT_PROBABILITY = 0.5
static double CATCHABLE_AREA_L_STRETCH = 1.0
static std::string VIEW_MODE_WIDTH = "high"
static std::string VIEW_MODE_QUALITY = "normal"
static double STAMINA = 8000.0
static double EFFORT = 1.0
static double STAMINA_CAPACITY = 130600.0
static double AMOUNT_OF_SPEED = 0.0
static double DIRECTION_OF_SPEED = 0.0
static double HEAD_ANGLE = 0.0
static int KICK_COUNT = 0
static int DASH_COUNT = 0
static int TURN_COUNT = 0
static int SAY_COUNT = 0
static int TURN_NECK_COUNT = 0
static int CATCH_COUNT = 0
static int MOVE_COUNT = 0
static int CHANGE_VIEW_COUNT = 0
static int ARM_MOVABLE = 0
static int ARM_EXPIRES = 0
static double ARM_DIST = 0.0
static double ARM_DIR = 0.0
static int ARM_COUNT = 0
static std::string FOCUS_TARGET = "none"
static int FOCUS_COUNT = 0
static int TACKLE_EXPIRES = 0
static int TACKLE_COUNT = 0
static std::list< std::string > COLLISION
static int FOUL_CHARGED = 0
static std::string FOUL_CARD = "none"
Detailed Description
Self
The Self lorem Ipsum
Definition at line 45 of file Self.h.
Constructor & Destructor Documentation
Phoenix::Self::Self (std::string player_params, std::string team_name, int unum, std::string side)
Definition at line 225 of file Self.cpp.
References ALLOW_MULT_DEFAULT_TYPE, CATCHABLE_AREA_L_STRECH_MAX, CATCHABLE_AREA_L_STRECH_MIN, Phoenix::catchable_area_l_stretch, Phoenix::dash_power_rate, DASH_POWER_RATE_DELTA_MAX, DASH_POWER_RATE_DELTA_MIN, Phoenix::effort_max, EFFORT_MAX_DELTA_FACTOR, Phoenix::effort_min, EFFORT_MIN_DELTA_FACTOR, Phoenix::extra_stamina, EXTRA_STAMINA_DELTA_MAX, EXTRA_STAMINA_DELTA_MIN, Phoenix::foul_detect_probability, FOUL_DETECT_PROBABILITY_DELTA_FACTOR, Phoenix::getPlayerParameter(), Phoenix::inertia_moment, INERTIA_MOMENT_DELTA_FACTOR, Phoenix::Flag::initializeField(), Phoenix::kick_power_rate, KICK_POWER_RATE_DELTA_MAX, KICK_POWER_RATE_DELTA_MIN, Phoenix::kick_rand, KICK_RAND_DELTA_FACTOR, Phoenix::kickable_margin, KICKABLE_MARGIN_DELTA_MAX, KICKABLE_MARGIN_DELTA_MIN, NEW_DASH_POWER_RATE_DELTA_MAX, NEW_DASH_POWER_RATE_DELTA_MIN, NEW_STAMINA_INC_MAX_DELTA_FACTOR, Phoenix::player_decay, PLAYER_DECAY_DELTA_MAX, PLAYER_DECAY_DELTA_MIN, Phoenix::player_size, PLAYER_SIZE_DELTA_FACTOR, Phoenix::player_speed_max, PLAYER_SPEED_MAX_DELTA_MAX, PLAYER_SPEED_MAX_DELTA_MIN, PLAYER_TYPES, PT_MAX, RANDOM_SEED, SIDE, Phoenix::stamina_inc_max, STAMINA_INC_MAX_DELTA_FACTOR, SUBS_MAX, TEAM_NAME, Phoenix::theta, Phoenix::types_id, and UNIFORM_NUMBER.
Phoenix::Self::~Self ()
Definition at line 279 of file Self.cpp.
References Phoenix::catchable_area_l_stretch, Phoenix::dash_power_rate, Phoenix::effort_max, Phoenix::effort_min, Phoenix::extra_stamina, Phoenix::foul_detect_probability, Phoenix::inertia_moment, Phoenix::kick_power_rate, Phoenix::kick_rand, Phoenix::kickable_margin, Phoenix::player_decay, Phoenix::player_size, Phoenix::player_speed_max, Phoenix::stamina_inc_max, Phoenix::types_id, and Phoenix::Config::VERBOSE.
Member Function Documentation
void Phoenix::Self::addPlayerType (std::string player_type)
Definition at line 298 of file Self.cpp.
References Phoenix::catchable_area_l_stretch, Phoenix::dash_power_rate, Phoenix::effort_max, Phoenix::effort_min, Phoenix::extra_stamina, Phoenix::foul_detect_probability, Phoenix::getPlayerTypeParameter(), Phoenix::inertia_moment, Phoenix::kick_power_rate, Phoenix::kick_rand, Phoenix::kickable_margin, Phoenix::player_decay, Phoenix::player_size, Phoenix::player_speed_max, Phoenix::stamina_inc_max, and Phoenix::types_id.
void Phoenix::Self::changePlayerType (int type)
Definition at line 505 of file Self.cpp.
References Phoenix::catchable_area_l_stretch, CATCHABLE_AREA_L_STRETCH, Phoenix::dash_power_rate, DASH_POWER_RATE, Phoenix::effort_max, EFFORT_MAX, Phoenix::effort_min, EFFORT_MIN, Phoenix::extra_stamina, EXTRA_STAMINA, Phoenix::foul_detect_probability, FOUL_DETECT_PROBABILITY, Phoenix::inertia_moment, INERTIA_MOMENT, Phoenix::kick_power_rate, KICK_POWER_RATE, Phoenix::kick_rand, KICK_RAND, Phoenix::kickable_margin, KICKABLE_MARGIN, Phoenix::player_decay, PLAYER_DECAY, Phoenix::player_size, PLAYER_SIZE, Phoenix::player_speed_max, PLAYER_SPEED_MAX, PLAYER_TYPES, Phoenix::stamina_inc_max, and STAMINA_INC_MAX.
double Phoenix::Self::getAmountOfSpeedAtTime (unsigned int time) static
Definition at line 746 of file Self.cpp.
References Phoenix::amount_of_speed_buffer(), and Phoenix::Config::BUFFER_MAX_HISTORY.
Referenced by localize().
int Phoenix::Self::getArmCountAtTime (unsigned int time) static
Definition at line 802 of file Self.cpp.
References Phoenix::arm_count_buffer(), and Phoenix::Config::BUFFER_MAX_HISTORY.
Referenced by processSenseBody().
double Phoenix::Self::getArmDirAtTime (unsigned int time) static
Definition at line 798 of file Self.cpp.
References Phoenix::arm_dir_buffer(), and Phoenix::Config::BUFFER_MAX_HISTORY.
double Phoenix::Self::getArmDistAtTime (unsigned int time) static
Definition at line 794 of file Self.cpp.
References Phoenix::arm_dist_buffer(), and Phoenix::Config::BUFFER_MAX_HISTORY.
int Phoenix::Self::getArmExpiresAtTime (unsigned int time) static
Definition at line 790 of file Self.cpp.
References Phoenix::arm_expires_buffer(), and Phoenix::Config::BUFFER_MAX_HISTORY.
int Phoenix::Self::getArmMovableAtTime (unsigned int time) static
Definition at line 786 of file Self.cpp.
References Phoenix::arm_movable_buffer(), and Phoenix::Config::BUFFER_MAX_HISTORY.
int Phoenix::Self::getCatchCountAtTime (unsigned int time) static
Definition at line 774 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::catch_count_buffer().
Referenced by processSenseBody().
int Phoenix::Self::getChangeViewCountAtTime (unsigned int time) static
Definition at line 782 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::change_view_count_buffer().
Referenced by processSenseBody().
std::list< std::string > Phoenix::Self::getCollisionsAtTime (unsigned int time) static
Definition at line 822 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, Phoenix::collisions_buffer(), and Phoenix::empty_vector.
int Phoenix::Self::getDashCountAtTime (unsigned int time) static
Definition at line 758 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::dash_count_buffer().
Referenced by processSenseBody().
double Phoenix::Self::getDirectionOfSpeedAtTime (unsigned int time) static
Definition at line 750 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::direction_of_speed_buffer().
Referenced by localize().
double Phoenix::Self::getEffortAtTime (unsigned int time) static
Definition at line 738 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::effort_buffer().
Referenced by localize().
int Phoenix::Self::getFocusCountAtTime (unsigned int time) static
Definition at line 810 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::focus_count_buffer().
std::string Phoenix::Self::getFocusTargetAtTime (unsigned int time) static
Definition at line 806 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::focus_target_buffer().
std::string Phoenix::Self::getFoulCardAtTime (unsigned int time) static
Definition at line 830 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::foul_card_buffer().
int Phoenix::Self::getFoulChargedAtTime (unsigned int time) static
Definition at line 826 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::foul_charged_buffer().
static double Phoenix::Self::getHeadAngleAtTime (unsigned int time) static
int Phoenix::Self::getKickCountAtTime (unsigned int time) static
Definition at line 754 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::kick_count_buffer().
Referenced by processSenseBody().
int Phoenix::Self::getMoveCountAtTime (unsigned int time) static
Definition at line 778 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::move_count_buffer().
Referenced by processSenseBody().
Position Phoenix::Self::getPosition () static
Definition at line 714 of file Self.cpp.
References Phoenix::theta, Phoenix::x, and Phoenix::y.
Referenced by Phoenix::Actions::goTo(), Phoenix::BeforeKickOff::onPlayerExecute(), Phoenix::PlayOn::onPlayerExecute(), Phoenix::process_see(), Phoenix::PlayOn::setup(), and Phoenix::World::updateWorld().
int Phoenix::Self::getSayCountAtTime (unsigned int time) static
Definition at line 766 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::say_count_buffer().
Referenced by processSenseBody().
double Phoenix::Self::getStaminaAtTime (unsigned int time) static
Definition at line 734 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::stamina_buffer().
double Phoenix::Self::getStaminaCapacityAtTime (unsigned int time) static
Definition at line 742 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::stamina_capacity_buffer().
int Phoenix::Self::getTackleCountAtTime (unsigned int time) static
Definition at line 818 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::tackle_count_buffer().
Referenced by processSenseBody().
int Phoenix::Self::getTackleExpiresAtTime (unsigned int time) static
Definition at line 814 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::tackle_expires_buffer().
int Phoenix::Self::getTurnCountAtTime (unsigned int time) static
Definition at line 762 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::turn_count_buffer().
Referenced by processSenseBody().
int Phoenix::Self::getTurnNeckCountAtTime (unsigned int time) static
Definition at line 770 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::turn_neck_count_buffer().
Referenced by processSenseBody().
Vector2D Phoenix::Self::getVelocity () static
Definition at line 718 of file Self.cpp.
References AMOUNT_OF_SPEED, DIRECTION_OF_SPEED, and Phoenix::Vector2D::getVector2DWithMagnitudeAndDirection().
Referenced by Phoenix::process_see().
std::string Phoenix::Self::getViewModeQualityAtTime (unsigned int time) static
Definition at line 730 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::view_mode_quality_buffer().
std::string Phoenix::Self::getViewModeWidthAtTime (unsigned int time) static
Definition at line 726 of file Self.cpp.
References Phoenix::Config::BUFFER_MAX_HISTORY, and Phoenix::view_mode_width_buffer().
void Phoenix::Self::localize (std::vector< Flag > flags)
Definition at line 624 of file Self.cpp.
References Phoenix::angleMean(), localize(), PI, Phoenix::positioned, Phoenix::theta, Phoenix::x, and Phoenix::y.
Referenced by Phoenix::process_see(), and Phoenix::process_sense_body().
void Phoenix::Self::localize ()
Definition at line 696 of file Self.cpp.
References Phoenix::Server::DASH_POWER_RATE, getAmountOfSpeedAtTime(), getDirectionOfSpeedAtTime(), getEffortAtTime(), Phoenix::Vector2D::getMagnitude(), Phoenix::Vector2D::getVector2DWithMagnitudeAndDirection(), Phoenix::Vector2D::getXComponent(), Phoenix::Vector2D::getYComponent(), INERTIA_MOMENT, Phoenix::Server::PLAYER_ACCEL_MAX, PLAYER_SPEED_MAX, Phoenix::positioned, Phoenix::theta, Phoenix::u, Phoenix::x, and Phoenix::y.
Referenced by localize().
void Phoenix::Self::processSenseBody (std::string sense_body)
Definition at line 317 of file Self.cpp.
References AMOUNT_OF_SPEED, Phoenix::amount_of_speed_buffer(), ARM_COUNT, Phoenix::arm_count_buffer(), ARM_DIR, Phoenix::arm_dir_buffer(), ARM_DIST, Phoenix::arm_dist_buffer(), ARM_EXPIRES, Phoenix::arm_expires_buffer(), ARM_MOVABLE, Phoenix::arm_movable_buffer(), Phoenix::CATCH, CATCH_COUNT, Phoenix::catch_count_buffer(), Phoenix::CHANGE_VIEW, CHANGE_VIEW_COUNT, Phoenix::change_view_count_buffer(), Phoenix::Command::changeStatusTo(), COLLISION, Phoenix::collisions_buffer(), Phoenix::DASH, DASH_COUNT, Phoenix::dash_count_buffer(), DIRECTION_OF_SPEED, Phoenix::direction_of_speed_buffer(), EFFORT, Phoenix::effort_buffer(), Phoenix::EXECUTED, FOCUS_COUNT, Phoenix::focus_count_buffer(), FOCUS_TARGET, Phoenix::focus_target_buffer(), FOUL_CARD, Phoenix::foul_card_buffer(), FOUL_CHARGED, Phoenix::foul_charged_buffer(), getArmCountAtTime(), getCatchCountAtTime(), getChangeViewCountAtTime(), getDashCountAtTime(), Phoenix::Command::getDashDirection(), Phoenix::Command::getDashPower(), getKickCountAtTime(), getMoveCountAtTime(), Phoenix::Command::getMoveX(), Phoenix::Command::getMoveY(), getSayCountAtTime(), getTackleCountAtTime(), getTurnCountAtTime(), Phoenix::Command::getTurnMoment(), getTurnNeckCountAtTime(), HEAD_ANGLE, Phoenix::head_angle_buffer(), Phoenix::KICK, KICK_COUNT, Phoenix::kick_count_buffer(), Phoenix::last_commands_sent, Phoenix::MOVE, MOVE_COUNT, Phoenix::move_count_buffer(), Phoenix::POINT, Phoenix::positioned, Phoenix::SAY, SAY_COUNT, Phoenix::say_count_buffer(), Phoenix::sense_body_regex(), STAMINA, Phoenix::stamina_buffer(), STAMINA_CAPACITY, Phoenix::stamina_capacity_buffer(), Phoenix::TACKLE, TACKLE_COUNT, Phoenix::tackle_count_buffer(), TACKLE_EXPIRES, Phoenix::tackle_expires_buffer(), Phoenix::TURN, TURN_COUNT, Phoenix::turn_count_buffer(), Phoenix::TURN_NECK, TURN_NECK_COUNT, Phoenix::turn_neck_count_buffer(), Phoenix::u, VIEW_MODE_QUALITY, Phoenix::view_mode_quality_buffer(), VIEW_MODE_WIDTH, Phoenix::view_mode_width_buffer(), Phoenix::x, and Phoenix::y.
Referenced by Phoenix::process_sense_body().
void Phoenix::Self::setLastCommandsSet (std::list< Command * > last_commands_sent) static
Definition at line 722 of file Self.cpp.
References Phoenix::last_commands_sent.
Referenced by Phoenix::Commands::sendCommands().
Member Data Documentation
int Phoenix::Self::ALLOW_MULT_DEFAULT_TYPE = 0 static
Definition at line 51 of file Self.h.
Referenced by Self().
double Phoenix::Self::AMOUNT_OF_SPEED = 0.0 static
Definition at line 105 of file Self.h.
Referenced by getVelocity(), Phoenix::Actions::goTo(), and processSenseBody().
int Phoenix::Self::ARM_COUNT = 0 static
Definition at line 135 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::ARM_DIR = 0.0 static
Definition at line 133 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::ARM_DIST = 0.0 static
Definition at line 131 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::ARM_EXPIRES = 0 static
Definition at line 129 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::ARM_MOVABLE = 0 static
Definition at line 127 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::CATCH_COUNT = 0 static
Definition at line 121 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::CATCHABLE_AREA_L_STRECH_MAX = 1.3 static
Definition at line 52 of file Self.h.
Referenced by Self().
double Phoenix::Self::CATCHABLE_AREA_L_STRECH_MIN = 1.0 static
Definition at line 53 of file Self.h.
Referenced by Self().
double Phoenix::Self::CATCHABLE_AREA_L_STRETCH = 1.0 static
Definition at line 94 of file Self.h.
Referenced by changePlayerType().
int Phoenix::Self::CHANGE_VIEW_COUNT = 0 static
Definition at line 125 of file Self.h.
Referenced by processSenseBody().
std::list< std::string > Phoenix::Self::COLLISION static
Definition at line 145 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::DASH_COUNT = 0 static
Definition at line 113 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::DASH_POWER_RATE = 0.006 static
Definition at line 85 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::DASH_POWER_RATE_DELTA_MAX = 0.0 static
Definition at line 54 of file Self.h.
Referenced by Self().
double Phoenix::Self::DASH_POWER_RATE_DELTA_MIN = 0.0 static
Definition at line 55 of file Self.h.
Referenced by Self().
double Phoenix::Self::DIRECTION_OF_SPEED = 0.0 static
Definition at line 107 of file Self.h.
Referenced by getVelocity(), and processSenseBody().
double Phoenix::Self::EFFORT = 1.0 static
Definition at line 101 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::EFFORT_MAX = 1.0 static
Definition at line 90 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::EFFORT_MAX_DELTA_FACTOR = -0.004 static
Definition at line 56 of file Self.h.
Referenced by Self().
double Phoenix::Self::EFFORT_MIN = 0.6 static
Definition at line 91 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::EFFORT_MIN_DELTA_FACTOR = -0.004 static
Definition at line 57 of file Self.h.
Referenced by Self().
double Phoenix::Self::EXTRA_STAMINA = 50.0 static
Definition at line 89 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::EXTRA_STAMINA_DELTA_MAX = 50.0 static
Definition at line 58 of file Self.h.
Referenced by Self().
double Phoenix::Self::EXTRA_STAMINA_DELTA_MIN = 0.0 static
Definition at line 59 of file Self.h.
Referenced by Self().
int Phoenix::Self::FOCUS_COUNT = 0 static
Definition at line 139 of file Self.h.
Referenced by processSenseBody().
std::string Phoenix::Self::FOCUS_TARGET = "none" static
Definition at line 137 of file Self.h.
Referenced by processSenseBody().
std::string Phoenix::Self::FOUL_CARD = "none" static
Definition at line 149 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::FOUL_CHARGED = 0 static
Definition at line 147 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::FOUL_DETECT_PROBABILITY = 0.5 static
Definition at line 93 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::FOUL_DETECT_PROBABILITY_DELTA_FACTOR = 0.0 static
Definition at line 60 of file Self.h.
Referenced by Self().
double Phoenix::Self::HEAD_ANGLE = 0.0 static
Definition at line 109 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::INERTIA_MOMENT = 5.0 static
Definition at line 84 of file Self.h.
Referenced by changePlayerType(), Phoenix::Actions::goTo(), and localize().
double Phoenix::Self::INERTIA_MOMENT_DELTA_FACTOR = 25.0 static
Definition at line 61 of file Self.h.
Referenced by Self().
int Phoenix::Self::KICK_COUNT = 0 static
Definition at line 111 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::KICK_POWER_RATE = 0.027 static
Definition at line 92 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::KICK_POWER_RATE_DELTA_MAX = 0.0 static
Definition at line 62 of file Self.h.
Referenced by Self().
double Phoenix::Self::KICK_POWER_RATE_DELTA_MIN = 0.0 static
Definition at line 63 of file Self.h.
Referenced by Self().
double Phoenix::Self::KICK_RAND = 0.1 static
Definition at line 88 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::KICK_RAND_DELTA_FACTOR = 1.0 static
Definition at line 64 of file Self.h.
Referenced by Self().
double Phoenix::Self::KICKABLE_MARGIN = 0.7 static
Definition at line 87 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::KICKABLE_MARGIN_DELTA_MAX = 0.1 static
Definition at line 65 of file Self.h.
Referenced by Self().
double Phoenix::Self::KICKABLE_MARGIN_DELTA_MIN = -0.1 static
Definition at line 66 of file Self.h.
Referenced by Self().
int Phoenix::Self::MOVE_COUNT = 0 static
Definition at line 123 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::NEW_DASH_POWER_RATE_DELTA_MAX = 0.0008 static
Definition at line 67 of file Self.h.
Referenced by Self().
double Phoenix::Self::NEW_DASH_POWER_RATE_DELTA_MIN = -0.0012 static
Definition at line 68 of file Self.h.
Referenced by Self().
double Phoenix::Self::NEW_STAMINA_INC_MAX_DELTA_FACTOR = -6000.0 static
Definition at line 69 of file Self.h.
Referenced by Self().
double Phoenix::Self::PI = 3.14159265359 static
Definition at line 47 of file Self.h.
Referenced by Phoenix::angleMean(), Phoenix::Ball::Ball(), Phoenix::Position::getDirectionTo(), Phoenix::Vector2D::getVector2DWithMagnitudeAndDirection(), localize(), Phoenix::Vector2D::operator*(), Phoenix::Player::Player(), Phoenix::triangular(), and Phoenix::Vector2D::Vector2D().
double Phoenix::Self::PLAYER_DECAY = 0.4 static
Definition at line 83 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::PLAYER_DECAY_DELTA_MAX = 0.1 static
Definition at line 70 of file Self.h.
Referenced by Self().
double Phoenix::Self::PLAYER_DECAY_DELTA_MIN = -0.1 static
Definition at line 71 of file Self.h.
Referenced by Self().
double Phoenix::Self::PLAYER_SIZE = 0.3 static
Definition at line 86 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::PLAYER_SIZE_DELTA_FACTOR = -100.0 static
Definition at line 72 of file Self.h.
Referenced by Self().
double Phoenix::Self::PLAYER_SPEED_MAX = 1.05 static
Definition at line 81 of file Self.h.
Referenced by changePlayerType(), and localize().
double Phoenix::Self::PLAYER_SPEED_MAX_DELTA_MAX = 0.0 static
Definition at line 73 of file Self.h.
Referenced by Self().
double Phoenix::Self::PLAYER_SPEED_MAX_DELTA_MIN = 0.0 static
Definition at line 74 of file Self.h.
Referenced by Self().
int Phoenix::Self::PLAYER_TYPES = 18 static
Definition at line 75 of file Self.h.
Referenced by changePlayerType(), Phoenix::Controller::connect(), and Self().
int Phoenix::Self::PT_MAX = 1 static
Definition at line 76 of file Self.h.
Referenced by Self().
int Phoenix::Self::RANDOM_SEED = 1325632690 static
Definition at line 77 of file Self.h.
Referenced by Self().
int Phoenix::Self::SAY_COUNT = 0 static
Definition at line 117 of file Self.h.
Referenced by processSenseBody().
std::string Phoenix::Self::SIDE = "l" static
Definition at line 50 of file Self.h.
Referenced by Phoenix::makeCoordinate(), Phoenix::Parser::parseMessage(), Self(), and Phoenix::Game::updatePlayMode().
double Phoenix::Self::STAMINA = 8000.0 static
Definition at line 99 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::STAMINA_CAPACITY = 130600.0 static
Definition at line 103 of file Self.h.
Referenced by processSenseBody().
double Phoenix::Self::STAMINA_INC_MAX = 45.0 static
Definition at line 82 of file Self.h.
Referenced by changePlayerType().
double Phoenix::Self::STAMINA_INC_MAX_DELTA_FACTOR = 0.0 static
Definition at line 78 of file Self.h.
Referenced by Self().
int Phoenix::Self::SUBS_MAX = 3 static
Definition at line 79 of file Self.h.
Referenced by Self().
int Phoenix::Self::TACKLE_COUNT = 0 static
Definition at line 143 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::TACKLE_EXPIRES = 0 static
Definition at line 141 of file Self.h.
Referenced by processSenseBody().
std::string Phoenix::Self::TEAM_NAME = "Phoenix2D" static
Definition at line 48 of file Self.h.
Referenced by Phoenix::Config::load(), Phoenix::Logger::log(), Phoenix::Player::Player(), Self(), and Phoenix::PlayOn::setup().
int Phoenix::Self::TURN_COUNT = 0 static
Definition at line 115 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::TURN_NECK_COUNT = 0 static
Definition at line 119 of file Self.h.
Referenced by processSenseBody().
int Phoenix::Self::TYPE_ID = 0 static
Definition at line 80 of file Self.h.
int Phoenix::Self::UNIFORM_NUMBER = 1 static
Definition at line 49 of file Self.h.
Referenced by Phoenix::Config::load(), Phoenix::Logger::log(), Self(), and Phoenix::PlayOn::setup().
std::string Phoenix::Self::VIEW_MODE_QUALITY = "normal" static
Definition at line 97 of file Self.h.
Referenced by processSenseBody().
std::string Phoenix::Self::VIEW_MODE_WIDTH = "high" static
Definition at line 95 of file Self.h.
Referenced by processSenseBody(), and Phoenix::World::updateWorld().
The documentation for this class was generated from the following files:
Self.h
Self.cpp