Phoenix2D-Library: Phoenix::Reader Class Reference
Phoenix::Reader Class Reference
Phoenix Core Objects
Reader
The Reader lorem Ipsum
#include <Reader.h>
Public Member Functions
Reader (Connect *connect, Parser *parser)
~Reader ()
bool isRunning ()
void start ()
void execute ()
void stop ()
Detailed Description
Reader
The Reader lorem Ipsum
Definition at line 39 of file Reader.h.
Constructor & Destructor Documentation
Phoenix::Reader::Reader (Connect * connect, Parser * parser)
Definition at line 41 of file Reader.cpp.
References Phoenix::connect_ptr, and Phoenix::parser_ptr.
Phoenix::Reader::~Reader ()
Definition at line 46 of file Reader.cpp.
References Phoenix::Config::VERBOSE.
Member Function Documentation
void Phoenix::Reader::execute ()
Definition at line 50 of file Reader.cpp.
References Phoenix::connect_ptr, Phoenix::Parser::parseMessage(), Phoenix::parser_ptr, Phoenix::Connect::receiveMessage(), and Phoenix::running.
Referenced by Phoenix::run().
bool Phoenix::Reader::isRunning ()
Definition at line 56 of file Reader.cpp.
References Phoenix::running.
void Phoenix::Reader::start ()
Definition at line 60 of file Reader.cpp.
References Phoenix::run(), Phoenix::running, and Phoenix::thread.
Referenced by Phoenix::Controller::connect().
void Phoenix::Reader::stop ()
Definition at line 69 of file Reader.cpp.
References Phoenix::connect_ptr, Phoenix::Connect::disconnect(), Phoenix::running, Phoenix::Connect::sendMessage(), and Phoenix::thread.
Referenced by Phoenix::Controller::disconnect().
The documentation for this class was generated from the following files:
Reader.h
Reader.cpp