Phoenix2D-Library: Phoenix::WorldModel Class Reference
Phoenix::WorldModel Class Reference
WorldModel
The WorldModel lorem Ipsum
#include <WorldModel.h>
Public Member Functions
WorldModel (std::list< Player > players, Ball ball)
~WorldModel ()
std::list< Player * > getPlayers ()
std::list< Player * > getPlayersOrderedByDistanceTo (Position position)
std::list< Player * > getOurPlayers ()
std::list< Player * > getOurPlayersOrderedByDistanceTo (Position position)
std::list< Player * > getOppPlayers ()
std::list< Player * > getOppPlayersOrderedByDistanceTo (Position position)
std::list< Player * > getUndPlayers ()
std::list< Player * > getUndPlayersOrderedByDistanceTo (Position position)
Ball * getBall ()
Private Attributes
std::list< Player > players
Ball ball
Detailed Description
WorldModel
The WorldModel lorem Ipsum
Definition at line 38 of file WorldModel.h.
Constructor & Destructor Documentation
Phoenix::WorldModel::WorldModel (std::list< Player > players, Ball ball)
Definition at line 33 of file WorldModel.cpp.
References ball, and players.
Phoenix::WorldModel::~WorldModel ()
Definition at line 38 of file WorldModel.cpp.
Member Function Documentation
Ball * Phoenix::WorldModel::getBall ()
Definition at line 126 of file WorldModel.cpp.
References ball.
std::list< Player * > Phoenix::WorldModel::getOppPlayers ()
Definition at line 82 of file WorldModel.cpp.
References players.
std::list< Player * > Phoenix::WorldModel::getOppPlayersOrderedByDistanceTo (Position position)
Definition at line 92 of file WorldModel.cpp.
References Phoenix::compareDistances(), players, and Phoenix::positionToCompare.
std::list< Player * > Phoenix::WorldModel::getOurPlayers ()
Definition at line 60 of file WorldModel.cpp.
References players.
std::list< Player * > Phoenix::WorldModel::getOurPlayersOrderedByDistanceTo (Position position)
Definition at line 70 of file WorldModel.cpp.
References Phoenix::compareDistances(), players, and Phoenix::positionToCompare.
std::list< Player * > Phoenix::WorldModel::getPlayers ()
Definition at line 42 of file WorldModel.cpp.
References players.
Referenced by Phoenix::Trainer::execute(), Phoenix::PlayOn::onPlayerExecute(), and Phoenix::PlayOn::setup().
std::list< Player * > Phoenix::WorldModel::getPlayersOrderedByDistanceTo (Position position)
Definition at line 50 of file WorldModel.cpp.
References Phoenix::compareDistances(), players, and Phoenix::positionToCompare.
std::list< Player * > Phoenix::WorldModel::getUndPlayers ()
Definition at line 104 of file WorldModel.cpp.
References players.
std::list< Player * > Phoenix::WorldModel::getUndPlayersOrderedByDistanceTo (Position position)
Definition at line 114 of file WorldModel.cpp.
References Phoenix::compareDistances(), players, and Phoenix::positionToCompare.
Member Data Documentation
Ball Phoenix::WorldModel::ball private
Definition at line 40 of file WorldModel.h.
Referenced by getBall(), and WorldModel().
std::list<Player> Phoenix::WorldModel::players private
Definition at line 39 of file WorldModel.h.
Referenced by getOppPlayers(), getOppPlayersOrderedByDistanceTo(), getOurPlayers(), getOurPlayersOrderedByDistanceTo(), getPlayers(), getPlayersOrderedByDistanceTo(), getUndPlayers(), getUndPlayersOrderedByDistanceTo(), and WorldModel().
The documentation for this class was generated from the following files:
WorldModel.h
WorldModel.cpp