Phoenix2D-Library: Phoenix::Commands Class Reference
Phoenix::Commands Class Reference
Phoenix Core Objects
Commands
The Commans lorem Ipsum
#include <Commands.h>
Public Member Functions
Commands (Connect *connect)
~Commands ()
void flush ()
void move (double x, double y)
void turn (double moment)
void turnNeck (double moment)
void dash (double power, double direction)
void say (std::string message)
void catchBall (double direction)
void kick (double power, double direction)
void tackle (double power, bool willToFoul)
void pointTo (double distance, double direction)
void changeView (std::string width)
void moveObject (std::string object, double x, double y)
void changeMode (std::string mode)
void start ()
void recover ()
int sendCommands ()
Detailed Description
Commands
The Commans lorem Ipsum
Definition at line 42 of file Commands.h.
Constructor & Destructor Documentation
Phoenix::Commands::Commands (Connect * connect)
Definition at line 38 of file Commands.cpp.
References Phoenix::commands_connect_ptr.
Phoenix::Commands::~Commands ()
Definition at line 42 of file Commands.cpp.
References Phoenix::Config::VERBOSE.
Member Function Documentation
void Phoenix::Commands::catchBall (double direction)
Definition at line 119 of file Commands.cpp.
References Phoenix::CATCH, Phoenix::commands_history, and Phoenix::commands_to_send.
void Phoenix::Commands::changeMode (std::string mode)
Definition at line 175 of file Commands.cpp.
References Phoenix::CHANGE_MODE, Phoenix::commands_history, and Phoenix::commands_to_send.
Referenced by Phoenix::Trainer::execute().
void Phoenix::Commands::changeView (std::string width)
Definition at line 159 of file Commands.cpp.
References Phoenix::CHANGE_VIEW, Phoenix::commands_history, and Phoenix::commands_to_send.
Referenced by Phoenix::PlayOn::setup().
void Phoenix::Commands::dash (double power, double direction)
Definition at line 92 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, Phoenix::DASH, Phoenix::Server::MAXMOMENT, Phoenix::Server::MAXPOWER, Phoenix::Server::MINMOMENT, and Phoenix::Server::MINPOWER.
Referenced by Phoenix::Actions::goTo().
void Phoenix::Commands::flush ()
Definition at line 46 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::Config::COMMANDS_MAX_HISTORY, and Phoenix::Game::SIMULATION_TIME.
Referenced by Phoenix::PlayMode::onPreExecute().
void Phoenix::Commands::kick (double power, double direction)
Definition at line 129 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::KICK.
void Phoenix::Commands::move (double x, double y)
Definition at line 52 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::MOVE.
Referenced by Phoenix::BeforeKickOff::setup().
void Phoenix::Commands::moveObject (std::string object, double x, double y)
Definition at line 166 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::MOVE_OBJECT.
void Phoenix::Commands::pointTo (double distance, double direction)
Definition at line 149 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::POINT.
void Phoenix::Commands::recover ()
Definition at line 188 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::RECOVER.
Referenced by Phoenix::Trainer::execute().
void Phoenix::Commands::say (std::string message)
Definition at line 112 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::SAY.
Referenced by Phoenix::Trainer::execute().
int Phoenix::Commands::sendCommands ()
Definition at line 194 of file Commands.cpp.
References Phoenix::Command::changeStatusTo(), Phoenix::commands_connect_ptr, Phoenix::commands_to_send, Phoenix::Command::getCommand(), Phoenix::Command::getWeight(), Phoenix::Connect::sendMessage(), Phoenix::SENT, and Phoenix::Self::setLastCommandsSet().
Referenced by Phoenix::Trainer::execute(), and Phoenix::PlayMode::onPostExecute().
void Phoenix::Commands::start ()
Definition at line 182 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::START.
void Phoenix::Commands::tackle (double power, bool willToFoul)
Definition at line 139 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, and Phoenix::TACKLE.
void Phoenix::Commands::turn (double moment)
Definition at line 62 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, Phoenix::Server::MAXMOMENT, Phoenix::Server::MINMOMENT, and Phoenix::TURN.
Referenced by Phoenix::Actions::goTo(), and Phoenix::BeforeKickOff::onPlayerExecute().
void Phoenix::Commands::turnNeck (double moment)
Definition at line 77 of file Commands.cpp.
References Phoenix::commands_history, Phoenix::commands_to_send, Phoenix::Server::MAXMOMENT, Phoenix::Server::MINMOMENT, and Phoenix::TURN_NECK.
The documentation for this class was generated from the following files:
Commands.h
Commands.cpp