Phoenix2D-Library: Phoenix::World Class Reference
Phoenix::World Class Reference
Phoenix Core Objects
World
The World lorem Ipsum
#include <World.h>
Public Member Functions
World ()
~World ()
void updateWorld ()
void updateWorld (std::list< Player > players, Ball ball)
void updateObserverWorld (std::list< Player > players, Ball ball)
WorldModel getWorldModel ()
Detailed Description
World
The World lorem Ipsum
Definition at line 41 of file World.h.
Constructor & Destructor Documentation
Phoenix::World::World ()
Definition at line 33 of file World.cpp.
Phoenix::World::~World ()
Definition at line 37 of file World.cpp.
References Phoenix::Config::VERBOSE.
Member Function Documentation
WorldModel Phoenix::World::getWorldModel ()
Definition at line 104 of file World.cpp.
References Phoenix::ball, and Phoenix::players.
void Phoenix::World::updateObserverWorld (std::list< Player > players, Ball ball)
Definition at line 99 of file World.cpp.
References Phoenix::ball, and Phoenix::players.
Referenced by Phoenix::Parser::parseMessage().
void Phoenix::World::updateWorld ()
Definition at line 41 of file World.cpp.
References Phoenix::Self::getPosition(), Phoenix::players, and Phoenix::Self::VIEW_MODE_WIDTH.
Referenced by Phoenix::process_see(), and Phoenix::process_sense_body().
void Phoenix::World::updateWorld (std::list< Player > players, Ball ball)
Definition at line 57 of file World.cpp.
References Phoenix::ball, Phoenix::Player::boundTo(), Phoenix::Position::getDistanceTo(), Phoenix::Player::getPosition(), Phoenix::Self::getPosition(), Phoenix::Player::getPretenderFront(), Phoenix::Config::PLAYER_HISTORY, Phoenix::players, Phoenix::Player::pretendToBound(), and Phoenix::Self::VIEW_MODE_WIDTH.
The documentation for this class was generated from the following files:
World.h
World.cpp