Phoenix2D-Library: Phoenix::PlayMode Class Reference
Phoenix::PlayMode Class Reference abstract
Phoenix Play Modes
PlayMode
The PlayMode lorem Ipsum
#include <PlayMode.h>
Public Member Functions
PlayMode (Commands *commands)
virtual ~PlayMode ()
void onStart ()
virtual void setup (WorldModel world)=0
void onPreExecute ()
virtual void onPlayerExecute (WorldModel world)=0
virtual void onGoalieExecute (WorldModel world)=0
virtual void onCoachExecute (WorldModel world)=0
virtual void onMessageReceived (std::string message, int sender)=0
void onPostExecute ()
void onEnd ()
Protected Attributes
Commands * commands
Detailed Description
PlayMode
The PlayMode lorem Ipsum
Definition at line 59 of file PlayMode.h.
Constructor & Destructor Documentation
Phoenix::PlayMode::PlayMode (Commands * commands)
Definition at line 26 of file PlayMode.cpp.
References commands.
Phoenix::PlayMode::~PlayMode () virtual
Definition at line 30 of file PlayMode.cpp.
Member Function Documentation
virtual void Phoenix::PlayMode::onCoachExecute (WorldModel world) pure virtual
Implemented in Phoenix::PlayOn, Phoenix::BeforeKickOff, Phoenix::CornerKickL, Phoenix::FreeKickR, Phoenix::CornerKickR, Phoenix::FreeKickL, Phoenix::GoalKickL, Phoenix::KickInL, Phoenix::KickInR, Phoenix::KickOffL, Phoenix::KickOffR, and Phoenix::GoalKickR.
void Phoenix::PlayMode::onEnd ()
Definition at line 46 of file PlayMode.cpp.
virtual void Phoenix::PlayMode::onGoalieExecute (WorldModel world) pure virtual
Implemented in Phoenix::PlayOn, Phoenix::BeforeKickOff, Phoenix::CornerKickL, Phoenix::FreeKickR, Phoenix::CornerKickR, Phoenix::FreeKickL, Phoenix::GoalKickL, Phoenix::KickInL, Phoenix::KickInR, Phoenix::KickOffL, Phoenix::KickOffR, and Phoenix::GoalKickR.
virtual void Phoenix::PlayMode::onMessageReceived (std::string message, int sender) pure virtual
Implemented in Phoenix::PlayOn, Phoenix::BeforeKickOff, Phoenix::CornerKickL, Phoenix::FreeKickR, Phoenix::CornerKickR, Phoenix::FreeKickL, Phoenix::GoalKickL, Phoenix::KickInL, Phoenix::KickInR, Phoenix::KickOffL, Phoenix::KickOffR, and Phoenix::GoalKickR.
Referenced by Phoenix::Parser::parseMessage().
virtual void Phoenix::PlayMode::onPlayerExecute (WorldModel world) pure virtual
Implemented in Phoenix::PlayOn, Phoenix::BeforeKickOff, Phoenix::CornerKickL, Phoenix::FreeKickR, Phoenix::CornerKickR, Phoenix::FreeKickL, Phoenix::GoalKickL, Phoenix::KickInL, Phoenix::KickInR, Phoenix::KickOffL, Phoenix::KickOffR, and Phoenix::GoalKickR.
void Phoenix::PlayMode::onPostExecute ()
Definition at line 42 of file PlayMode.cpp.
References commands, and Phoenix::Commands::sendCommands().
void Phoenix::PlayMode::onPreExecute ()
Definition at line 38 of file PlayMode.cpp.
References commands, and Phoenix::Commands::flush().
void Phoenix::PlayMode::onStart ()
Definition at line 34 of file PlayMode.cpp.
References Phoenix::Parser::registerPlayMode().
virtual void Phoenix::PlayMode::setup (WorldModel world) pure virtual
Implemented in Phoenix::PlayOn, Phoenix::BeforeKickOff, Phoenix::CornerKickL, Phoenix::FreeKickR, Phoenix::CornerKickR, Phoenix::FreeKickL, Phoenix::GoalKickL, Phoenix::KickInL, Phoenix::KickInR, Phoenix::KickOffL, Phoenix::KickOffR, and Phoenix::GoalKickR.
Member Data Documentation
Commands* Phoenix::PlayMode::commands protected
Definition at line 61 of file PlayMode.h.
Referenced by Phoenix::BeforeKickOff::onPlayerExecute(), onPostExecute(), onPreExecute(), PlayMode(), Phoenix::BeforeKickOff::setup(), and Phoenix::PlayOn::setup().
The documentation for this class was generated from the following files:
PlayMode.h
PlayMode.cpp