Phoenix2D-Library: Phoenix::PlayOn Class Reference
Phoenix::PlayOn Class Reference
Phoenix Play Modes
PlayOn
The PlayOn lorem Ipsum
#include <PlayOn.h>
Public Member Functions
PlayOn (Commands *commands, Actions *actions)
~PlayOn ()
void setup (WorldModel world)
void onPlayerExecute (WorldModel world)
void onGoalieExecute (WorldModel world)
void onCoachExecute (WorldModel world)
void onMessageReceived (std::string message, int sender)
Public Member Functions inherited from Phoenix::PlayMode
PlayMode (Commands *commands)
virtual ~PlayMode ()
void onStart ()
void onPreExecute ()
void onPostExecute ()
void onEnd ()
Private Attributes
Actions * actions
Additional Inherited Members
Protected Attributes inherited from Phoenix::PlayMode
Commands * commands
Detailed Description
PlayOn
The PlayOn lorem Ipsum
Definition at line 43 of file PlayOn.h.
Constructor & Destructor Documentation
Phoenix::PlayOn::PlayOn (Commands * commands, Actions * actions)
Definition at line 36 of file PlayOn.cpp.
References actions.
Phoenix::PlayOn::~PlayOn ()
Definition at line 40 of file PlayOn.cpp.
Member Function Documentation
void Phoenix::PlayOn::onCoachExecute (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 108 of file PlayOn.cpp.
void Phoenix::PlayOn::onGoalieExecute (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 104 of file PlayOn.cpp.
void Phoenix::PlayOn::onMessageReceived (std::string message, int sender) virtual
Implements Phoenix::PlayMode.
Definition at line 112 of file PlayOn.cpp.
void Phoenix::PlayOn::onPlayerExecute (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 85 of file PlayOn.cpp.
References actions, Phoenix::Game::GAME_TIME, Phoenix::WorldModel::getPlayers(), Phoenix::Self::getPosition(), Phoenix::Actions::goTo(), Phoenix::Config::LOGGING, Phoenix::move, Phoenix::players, Phoenix::positions(), and Phoenix::Position::toString().
void Phoenix::PlayOn::setup (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 44 of file PlayOn.cpp.
References Phoenix::Commands::changeView(), Phoenix::PlayMode::commands, Phoenix::Game::GAME_TIME, Phoenix::WorldModel::getPlayers(), Phoenix::Self::getPosition(), Phoenix::Config::LOGGING, Phoenix::move, Phoenix::players, Phoenix::positions(), Phoenix::Self::TEAM_NAME, Phoenix::Position::toString(), and Phoenix::Self::UNIFORM_NUMBER.
Member Data Documentation
Actions* Phoenix::PlayOn::actions private
Definition at line 45 of file PlayOn.h.
Referenced by onPlayerExecute(), and PlayOn().
The documentation for this class was generated from the following files:
PlayOn.h
PlayOn.cpp