Phoenix2D-Library: Phoenix::Parser Class Reference
Phoenix::Parser Class Reference
Phoenix Core Objects
Parser
The Parser lorem Ipsum
#include <Parser.h>
Public Member Functions
Parser (Self *self, World *world)
~Parser ()
void parseMessage (std::string message)
Static Public Member Functions
static void registerPlayMode (PlayMode *play_mode)
static void registerTrainer (Trainer *trainer)
Detailed Description
Parser
The Parser lorem Ipsum
Definition at line 44 of file Parser.h.
Constructor & Destructor Documentation
Phoenix::Parser::Parser (Self * self, World * world)
Definition at line 183 of file Parser.cpp.
References Phoenix::attr, Phoenix::game_ptr, Phoenix::self_ptr, and Phoenix::world_ptr.
Phoenix::Parser::~Parser ()
Definition at line 191 of file Parser.cpp.
References Phoenix::attr, Phoenix::game_ptr, and Phoenix::Config::VERBOSE.
Member Function Documentation
void Phoenix::Parser::parseMessage (std::string message)
Definition at line 197 of file Parser.cpp.
References Phoenix::attr, Phoenix::ball, Phoenix::game_ptr, Phoenix::hear_coach_regex(), Phoenix::hear_player_regex(), Phoenix::hear_referee_regex(), Phoenix::hear_trainer_regex(), Phoenix::PlayMode::onMessageReceived(), Phoenix::play_mode_ptr, Phoenix::players, Phoenix::process_see(), Phoenix::process_sense_body(), Phoenix::processing_body, Phoenix::processing_see, Phoenix::see_message, Phoenix::see_received, Phoenix::see_regex(), Phoenix::sense_body_message, Phoenix::Self::SIDE, Phoenix::Game::SIMULATION_TIME, Phoenix::thread_see, Phoenix::thread_sense_body, Phoenix::World::updateObserverWorld(), Phoenix::Game::updatePlayMode(), Phoenix::Game::updateTime(), Phoenix::Config::VERBOSE, and Phoenix::world_ptr.
Referenced by Phoenix::Reader::execute().
void Phoenix::Parser::registerPlayMode (PlayMode * play_mode) static
Definition at line 276 of file Parser.cpp.
References Phoenix::play_mode_ptr.
Referenced by Phoenix::PlayMode::onStart().
void Phoenix::Parser::registerTrainer (Trainer * trainer) static
Definition at line 280 of file Parser.cpp.
References Phoenix::trainer_ptr.
The documentation for this class was generated from the following files:
Parser.h
Parser.cpp