Phoenix2D-Library: Phoenix::Trainer Class Reference
Phoenix::Trainer Class Reference
Trainer
The Trainer lorem Ipsum
#include <Trainer.h>
Public Member Functions
Trainer (Commands *commands)
~Trainer ()
void execute (WorldModel world)
bool continueExecution ()
Private Attributes
Commands * commands
bool newExecution
Detailed Description
Trainer
The Trainer lorem Ipsum
Definition at line 39 of file Trainer.h.
Constructor & Destructor Documentation
Phoenix::Trainer::Trainer (Commands * commands)
Definition at line 128 of file Trainer.cpp.
References commands, Phoenix::generateCode(), Phoenix::loadCode(), and newExecution.
Phoenix::Trainer::~Trainer ()
Definition at line 140 of file Trainer.cpp.
Member Function Documentation
bool Phoenix::Trainer::continueExecution ()
Definition at line 192 of file Trainer.cpp.
References newExecution.
void Phoenix::Trainer::execute (WorldModel world)
Definition at line 144 of file Trainer.cpp.
References Phoenix::execution_line::accum, Phoenix::execution_line::arg, Phoenix::CHANGE_TO, Phoenix::Commands::changeMode(), Phoenix::execution_line::command, commands, Phoenix::DO, Phoenix::END, Phoenix::END_DO, Phoenix::Game::GAME_TIME, Phoenix::WorldModel::getPlayers(), Phoenix::execution_line::jump_to, newExecution, Phoenix::Game::PLAY_MODE, Phoenix::players, Phoenix::program, Phoenix::Commands::recover(), Phoenix::RECOVER, Phoenix::Commands::say(), Phoenix::SAY, Phoenix::Commands::sendCommands(), Phoenix::START, and Phoenix::Config::TRAINER_LOGGING.
Member Data Documentation
Commands* Phoenix::Trainer::commands private
Definition at line 40 of file Trainer.h.
Referenced by execute(), and Trainer().
bool Phoenix::Trainer::newExecution private
Definition at line 41 of file Trainer.h.
Referenced by continueExecution(), execute(), and Trainer().
The documentation for this class was generated from the following files:
Trainer.h
Trainer.cpp