Phoenix2D-Library: Phoenix::Actions Class Reference
Phoenix::Actions Class Reference
Actions
The Actions lorem Ipsum
#include <Actions.h>
Public Types
enum ACTION {
GO_TO, DRIBBLE_TO, HOLD_POSITION, PASS_TO_SECTION,
ATTACK_SECTION
}
Public Member Functions
Actions (Commands *commands)
~Actions ()
bool goTo (Position position)
void dribbleTo (Position position)
void holdPosition (Position position)
void passToSection (Position position)
void attackSection (Position position)
Public Attributes
Commands * commands
Detailed Description
Actions
The Actions lorem Ipsum
Definition at line 38 of file Actions.h.
Member Enumeration Documentation
enum Phoenix::Actions::ACTION
Enumerator
GO_TO
DRIBBLE_TO
HOLD_POSITION
PASS_TO_SECTION
ATTACK_SECTION
Definition at line 40 of file Actions.h.
Constructor & Destructor Documentation
Phoenix::Actions::Actions (Commands * commands)
Definition at line 29 of file Actions.cpp.
References commands.
Phoenix::Actions::~Actions ()
Definition at line 33 of file Actions.cpp.
Member Function Documentation
void Phoenix::Actions::attackSection (Position position)
Definition at line 66 of file Actions.cpp.
void Phoenix::Actions::dribbleTo (Position position)
Definition at line 54 of file Actions.cpp.
bool Phoenix::Actions::goTo (Position position)
Definition at line 37 of file Actions.cpp.
References Phoenix::Self::AMOUNT_OF_SPEED, commands, Phoenix::Commands::dash(), Phoenix::Position::getDirectionTo(), Phoenix::Position::getDistanceTo(), Phoenix::Self::getPosition(), Phoenix::Self::INERTIA_MOMENT, and Phoenix::Commands::turn().
Referenced by Phoenix::PlayOn::onPlayerExecute().
void Phoenix::Actions::holdPosition (Position position)
Definition at line 58 of file Actions.cpp.
void Phoenix::Actions::passToSection (Position position)
Definition at line 62 of file Actions.cpp.
Member Data Documentation
Commands* Phoenix::Actions::commands
Definition at line 47 of file Actions.h.
Referenced by Actions(), and goTo().
The documentation for this class was generated from the following files:
Actions.h
Actions.cpp