Phoenix2D-Library: Phoenix::Vector2D Class Reference
Phoenix::Vector2D Class Reference
Vector2D
The Vector2D lorem Ipsum
#include <Vector2D.h>
Public Member Functions
Vector2D ()
Vector2D (double x, double y)
~Vector2D ()
double getXComponent ()
double getYComponent ()
double getMagnitude ()
double getDirection ()
Vector2D operator+ (Vector2D vector)
Vector2D operator* (double scalar)
std::string toString ()
VECTOR_TYPE getType ()
Static Public Member Functions
static Vector2D getEmptyVector ()
static Vector2D getVector2DWithXAndY (double dx, double dy)
static Vector2D getVector2DWithMagnitudeAndDirection (double magnitude, double direction)
Private Attributes
double dx
double dy
double magnitude
double direction
VECTOR_TYPE type
Detailed Description
Vector2D
The Vector2D lorem Ipsum
Definition at line 45 of file Vector2D.h.
Constructor & Destructor Documentation
Phoenix::Vector2D::Vector2D ()
Definition at line 29 of file Vector2D.cpp.
References direction, dx, dy, Phoenix::EMPTY_V, magnitude, and type.
Referenced by getEmptyVector(), getVector2DWithMagnitudeAndDirection(), getVector2DWithXAndY(), operator*(), and operator+().
Phoenix::Vector2D::Vector2D (double x, double y)
Definition at line 37 of file Vector2D.cpp.
References direction, dx, dy, magnitude, Phoenix::Self::PI, type, Phoenix::V2D, Phoenix::x, and Phoenix::y.
Phoenix::Vector2D::~Vector2D ()
Definition at line 45 of file Vector2D.cpp.
Member Function Documentation
double Phoenix::Vector2D::getDirection ()
Definition at line 75 of file Vector2D.cpp.
References direction.
Vector2D Phoenix::Vector2D::getEmptyVector () static
Definition at line 49 of file Vector2D.cpp.
References Vector2D().
Referenced by Phoenix::Player::Player().
double Phoenix::Vector2D::getMagnitude ()
Definition at line 71 of file Vector2D.cpp.
References magnitude.
Referenced by Phoenix::Self::localize().
VECTOR_TYPE Phoenix::Vector2D::getType ()
Definition at line 103 of file Vector2D.cpp.
References type.
Vector2D Phoenix::Vector2D::getVector2DWithMagnitudeAndDirection (double magnitude, double direction) static
Definition at line 53 of file Vector2D.cpp.
References Phoenix::Self::PI, Vector2D(), Phoenix::x, and Phoenix::y.
Referenced by Phoenix::Self::getVelocity(), and Phoenix::Self::localize().
Vector2D Phoenix::Vector2D::getVector2DWithXAndY (double dx, double dy) static
Definition at line 59 of file Vector2D.cpp.
References Vector2D().
Referenced by Phoenix::Ball::getVelocity(), and Phoenix::Player::Player().
double Phoenix::Vector2D::getXComponent ()
Definition at line 63 of file Vector2D.cpp.
References dx.
Referenced by Phoenix::Ball::Ball(), Phoenix::Self::localize(), and Phoenix::Player::Player().
double Phoenix::Vector2D::getYComponent ()
Definition at line 67 of file Vector2D.cpp.
References dy.
Referenced by Phoenix::Ball::Ball(), Phoenix::Self::localize(), and Phoenix::Player::Player().
Vector2D Phoenix::Vector2D::operator* (double scalar)
Definition at line 85 of file Vector2D.cpp.
References direction, magnitude, Phoenix::Self::PI, Vector2D(), Phoenix::x, and Phoenix::y.
Vector2D Phoenix::Vector2D::operator+ (Vector2D vector)
Definition at line 79 of file Vector2D.cpp.
References dx, dy, Vector2D(), Phoenix::x, and Phoenix::y.
std::string Phoenix::Vector2D::toString ()
Definition at line 91 of file Vector2D.cpp.
References dx, dy, Phoenix::EMPTY_V, and type.
Member Data Documentation
double Phoenix::Vector2D::direction private
Definition at line 49 of file Vector2D.h.
Referenced by getDirection(), operator*(), and Vector2D().
double Phoenix::Vector2D::dx private
Definition at line 46 of file Vector2D.h.
Referenced by getXComponent(), operator+(), toString(), and Vector2D().
double Phoenix::Vector2D::dy private
Definition at line 47 of file Vector2D.h.
Referenced by getYComponent(), operator+(), toString(), and Vector2D().
double Phoenix::Vector2D::magnitude private
Definition at line 48 of file Vector2D.h.
Referenced by getMagnitude(), operator*(), and Vector2D().
VECTOR_TYPE Phoenix::Vector2D::type private
Definition at line 50 of file Vector2D.h.
Referenced by getType(), toString(), and Vector2D().
The documentation for this class was generated from the following files:
Vector2D.h
Vector2D.cpp