Phoenix2D-Library: Phoenix::BeforeKickOff Class Reference
Phoenix::BeforeKickOff Class Reference
Phoenix Play Modes
BeforeKickOff
The BeforeKickOff behavior lorem Ipsum
#include <BeforeKickOff.h>
Public Member Functions
BeforeKickOff (Commands *commands)
~BeforeKickOff ()
void setup (WorldModel world)
void onPlayerExecute (WorldModel world)
void onGoalieExecute (WorldModel world)
void onCoachExecute (WorldModel world)
void onMessageReceived (std::string message, int sender)
Public Member Functions inherited from Phoenix::PlayMode
PlayMode (Commands *commands)
virtual ~PlayMode ()
void onStart ()
void onPreExecute ()
void onPostExecute ()
void onEnd ()
Additional Inherited Members
Protected Attributes inherited from Phoenix::PlayMode
Commands * commands
Detailed Description
BeforeKickOff
The BeforeKickOff behavior lorem Ipsum
Definition at line 44 of file BeforeKickOff.h.
Constructor & Destructor Documentation
Phoenix::BeforeKickOff::BeforeKickOff (Commands * commands)
Definition at line 30 of file BeforeKickOff.cpp.
Phoenix::BeforeKickOff::~BeforeKickOff ()
Definition at line 34 of file BeforeKickOff.cpp.
Member Function Documentation
void Phoenix::BeforeKickOff::onCoachExecute (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 54 of file BeforeKickOff.cpp.
void Phoenix::BeforeKickOff::onGoalieExecute (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 50 of file BeforeKickOff.cpp.
void Phoenix::BeforeKickOff::onMessageReceived (std::string message, int sender) virtual
Implements Phoenix::PlayMode.
Definition at line 58 of file BeforeKickOff.cpp.
void Phoenix::BeforeKickOff::onPlayerExecute (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 43 of file BeforeKickOff.cpp.
References Phoenix::PlayMode::commands, Phoenix::Position::getBodyDirection(), Phoenix::Self::getPosition(), and Phoenix::Commands::turn().
void Phoenix::BeforeKickOff::setup (WorldModel world) virtual
Implements Phoenix::PlayMode.
Definition at line 38 of file BeforeKickOff.cpp.
References Phoenix::PlayMode::commands, Phoenix::Position::getX(), Phoenix::Position::getY(), Phoenix::Commands::move(), and Phoenix::Config::POSITION.
The documentation for this class was generated from the following files:
BeforeKickOff.h
BeforeKickOff.cpp