Phoenix2D-Library: Phoenix::Position Class Reference
Phoenix::Position Class Reference
Position
The Position lorem Ipsum
#include <Position.h>
Public Member Functions
Position ()
Position (double x, double y)
Position (double x, double y, double theta)
Position (double x, double y, double theta, double gamma)
~Position ()
double getX ()
double getY ()
double getBodyDirection ()
double getHeadDirection ()
double getDistanceTo (Position position)
double getDirectionTo (Position position)
void mirror ()
POSITION_TYPE getPositionType ()
std::string toString ()
Private Attributes
double x
double y
double theta
double gamma
POSITION_TYPE type
Detailed Description
Position
The Position lorem Ipsum
Definition at line 50 of file Position.h.
Constructor & Destructor Documentation
Phoenix::Position::Position ()
Definition at line 29 of file Position.cpp.
References Phoenix::EMPTY_P, gamma, theta, type, x, and y.
Phoenix::Position::Position (double x, double y)
Definition at line 37 of file Position.cpp.
References gamma, Phoenix::POINT_P, theta, type, x, and y.
Phoenix::Position::Position (double x, double y, double theta)
Definition at line 45 of file Position.cpp.
References gamma, Phoenix::OBJECT, theta, type, x, and y.
Phoenix::Position::Position (double x, double y, double theta, double gamma)
Definition at line 53 of file Position.cpp.
References Phoenix::COMPLETE, gamma, theta, type, x, and y.
Phoenix::Position::~Position ()
Definition at line 61 of file Position.cpp.
Member Function Documentation
double Phoenix::Position::getBodyDirection ()
Definition at line 73 of file Position.cpp.
References theta.
Referenced by Phoenix::Ball::Ball(), Phoenix::BeforeKickOff::onPlayerExecute(), and Phoenix::Player::Player().
double Phoenix::Position::getDirectionTo (Position position)
Definition at line 86 of file Position.cpp.
References gamma, getX(), getY(), Phoenix::Self::PI, theta, x, and y.
Referenced by Phoenix::Actions::goTo().
double Phoenix::Position::getDistanceTo (Position position)
Definition at line 81 of file Position.cpp.
References getX(), getY(), x, and y.
Referenced by Phoenix::compareDistances(), Phoenix::Actions::goTo(), and Phoenix::World::updateWorld().
double Phoenix::Position::getHeadDirection ()
Definition at line 77 of file Position.cpp.
References gamma.
Referenced by Phoenix::Ball::Ball(), and Phoenix::Player::Player().
POSITION_TYPE Phoenix::Position::getPositionType ()
Definition at line 101 of file Position.cpp.
References type.
double Phoenix::Position::getX ()
Definition at line 65 of file Position.cpp.
References x.
Referenced by Phoenix::Ball::Ball(), getDirectionTo(), getDistanceTo(), Phoenix::Player::Player(), and Phoenix::BeforeKickOff::setup().
double Phoenix::Position::getY ()
Definition at line 69 of file Position.cpp.
References y.
Referenced by Phoenix::Ball::Ball(), getDirectionTo(), getDistanceTo(), Phoenix::Player::Player(), and Phoenix::BeforeKickOff::setup().
void Phoenix::Position::mirror ()
Definition at line 96 of file Position.cpp.
References x, and y.
std::string Phoenix::Position::toString ()
Definition at line 105 of file Position.cpp.
References Phoenix::COMPLETE, Phoenix::EMPTY_P, gamma, Phoenix::OBJECT, Phoenix::POINT_P, theta, type, x, and y.
Referenced by Phoenix::PlayOn::onPlayerExecute(), and Phoenix::PlayOn::setup().
Member Data Documentation
double Phoenix::Position::gamma private
Definition at line 54 of file Position.h.
Referenced by getDirectionTo(), getHeadDirection(), Position(), and toString().
double Phoenix::Position::theta private
Definition at line 53 of file Position.h.
Referenced by getBodyDirection(), getDirectionTo(), Position(), and toString().
POSITION_TYPE Phoenix::Position::type private
Definition at line 55 of file Position.h.
Referenced by getPositionType(), Position(), and toString().
double Phoenix::Position::x private
Definition at line 51 of file Position.h.
Referenced by getDirectionTo(), getDistanceTo(), getX(), mirror(), Position(), and toString().
double Phoenix::Position::y private
Definition at line 52 of file Position.h.
Referenced by getDirectionTo(), getDistanceTo(), getY(), mirror(), Position(), and toString().
The documentation for this class was generated from the following files:
Position.h
Position.cpp